-- NOVELIGHT: Today's Book daily discovery surface.
-- Reader bookshelf state remains in reader_bookshelf_entries; this migration only
-- stores daily display/action evidence needed for once-per-day delivery, recent
-- suppression, and under-exposure weighting.

begin;

select pg_advisory_xact_lock(hashtext('novelight:20261003190000'));

create table public.reader_today_book_impressions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  novel_id bigint references public.novels(id) on delete set null,
  shown_on_jst date not null,
  shown_at timestamptz not null default now(),
  read_now_at timestamptz,
  read_later_at timestamptz,
  skipped_at timestamptz,
  swipe_read_later_at timestamptz,
  first_episode_arrival_at timestamptz,
  constraint reader_today_book_daily_once unique (user_id, shown_on_jst)
);

create index reader_today_book_novel_recent_idx
  on public.reader_today_book_impressions(novel_id, shown_at desc)
  where novel_id is not null;

create index reader_today_book_user_novel_recent_idx
  on public.reader_today_book_impressions(user_id, novel_id, shown_at desc)
  where novel_id is not null;

alter table public.reader_today_book_impressions enable row level security;
revoke all on table public.reader_today_book_impressions from public, anon, authenticated;
grant all on table public.reader_today_book_impressions to service_role;

comment on table public.reader_today_book_impressions is
  'Private Today''s Book daily delivery evidence. Never contributes to Rank, LIGHT SEED, SCOUT, or evaluation.';

create or replace function public.novelight_today_book_v1()
returns table (
  novel_id bigint,
  title text,
  description text,
  author_name text,
  genre text,
  thumbnail_url text,
  content_rating text,
  first_episode_id bigint
)
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_today date := (pg_catalog.now() at time zone 'Asia/Tokyo')::date;
  v_novel_id bigint;
begin
  if v_uid is null then
    return;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtext('novelight:today-book:' || v_uid::text || ':' || v_today::text)
  );

  if exists (
    select 1
      from public.reader_today_book_impressions i
     where i.user_id = v_uid
       and i.shown_on_jst = v_today
  ) then
    return;
  end if;

  select candidate.id
    into v_novel_id
    from (
      select
        n.id,
        pg_catalog.random() / (1.0 + (0.35 * pg_catalog.count(i7.id))) as selection_score
      from public.novels n
      join public.novel_rank_state rs
        on rs.novel_id_snapshot = n.id::text
       and rs.current_rank in (1, 2)
      left join public.reader_today_book_impressions i7
        on i7.novel_id = n.id
       and i7.shown_at >= pg_catalog.now() - interval '7 days'
      where n.status = 'published'
        and n.user_id <> v_uid
        -- No server-side verified-age attribute currently exists. Keep this
        -- automatic surface conservative so restricted works are never exposed
        -- to an ineligible account.
        and coalesce(n.content_rating, 'general') = 'general'
        and exists (
          select 1
            from public.episodes e
           where e.novel_id = n.id
             and e.status = 'published'
        )
        and not exists (
          select 1
            from public.reader_reading_progress rp
           where rp.user_id = v_uid
             and rp.novel_id = n.id
        )
        and not exists (
          select 1
            from public.reader_today_book_impressions recent
           where recent.user_id = v_uid
             and recent.novel_id = n.id
             and recent.shown_at >= pg_catalog.now() - interval '30 days'
        )
        and not exists (
          select 1
            from public.user_mutes m
           where m.muter_user_id = v_uid
             and m.muted_user_id = n.user_id
        )
        and not exists (
          select 1
            from public.user_blocks b
           where b.blocker_user_id = v_uid
             and b.blocked_user_id = n.user_id
        )
      group by n.id
      order by selection_score desc, n.id
      limit 1
    ) candidate;

  insert into public.reader_today_book_impressions(user_id, novel_id, shown_on_jst)
  values (v_uid, v_novel_id, v_today);

  if v_novel_id is null then
    return;
  end if;

  return query
  select
    n.id,
    n.title,
    coalesce(n.description, ''),
    coalesce(p.display_name, ''),
    coalesce(n.genre, ''),
    case when n.thumbnail_url like 'https://%' then n.thumbnail_url else null end,
    coalesce(n.content_rating, 'general'),
    first_episode.id
  from public.novels n
  join public.profiles p on p.id = n.user_id
  join lateral (
    select e.id
      from public.episodes e
     where e.novel_id = n.id
       and e.status = 'published'
     order by e.episode_number asc, e.id asc
     limit 1
  ) first_episode on true
  where n.id = v_novel_id
    and n.status = 'published';
end
$$;

revoke all on function public.novelight_today_book_v1() from public, anon;
grant execute on function public.novelight_today_book_v1() to authenticated;

create or replace function public.novelight_today_book_record_action_v1(
  p_novel_id bigint,
  p_action text
)
returns boolean
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_today date := (pg_catalog.now() at time zone 'Asia/Tokyo')::date;
  v_updated integer := 0;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  if p_novel_id is null then
    raise exception using errcode = '22023', message = 'Novel id is required';
  end if;
  if p_action not in ('read_now','read_later','skip','swipe_read_later','first_episode_arrival') then
    raise exception using errcode = '22023', message = 'Unsupported Today''s Book action';
  end if;

  update public.reader_today_book_impressions i
     set read_now_at = case when p_action = 'read_now' then coalesce(i.read_now_at, pg_catalog.now()) else i.read_now_at end,
         read_later_at = case when p_action in ('read_later','swipe_read_later') then coalesce(i.read_later_at, pg_catalog.now()) else i.read_later_at end,
         skipped_at = case when p_action = 'skip' then coalesce(i.skipped_at, pg_catalog.now()) else i.skipped_at end,
         swipe_read_later_at = case when p_action = 'swipe_read_later' then coalesce(i.swipe_read_later_at, pg_catalog.now()) else i.swipe_read_later_at end,
         first_episode_arrival_at = case when p_action = 'first_episode_arrival' then coalesce(i.first_episode_arrival_at, pg_catalog.now()) else i.first_episode_arrival_at end
   where i.user_id = v_uid
     and i.novel_id = p_novel_id
     and i.shown_on_jst = v_today;

  get diagnostics v_updated = row_count;
  return v_updated = 1;
end
$$;

revoke all on function public.novelight_today_book_record_action_v1(bigint, text) from public, anon;
grant execute on function public.novelight_today_book_record_action_v1(bigint, text) to authenticated;

commit;
