-- NOVELIGHT: author-owned work backup audit and server-side rate limiting.
--
-- Author backups are available to every plan. The database only records export
-- attempts and counts; exported manuscript text is never stored in this audit
-- table.

begin;

select pg_advisory_xact_lock(hashtext('novelight:20260917112000-author-backup-exports'));

create table if not exists public.author_backup_exports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  requested_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'started'
    check (status in ('started', 'completed', 'failed')),
  novel_count integer not null default 0 check (novel_count >= 0),
  episode_count integer not null default 0 check (episode_count >= 0)
);

create index if not exists author_backup_exports_user_requested_idx
  on public.author_backup_exports (user_id, requested_at desc);

alter table public.author_backup_exports enable row level security;

revoke all on table public.author_backup_exports from anon, authenticated;
revoke all on sequence public.author_backup_exports_id_seq from anon, authenticated;

drop function if exists public.novelight_begin_author_backup_export(uuid);

create function public.novelight_begin_author_backup_export(p_user_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_recent_count integer;
  v_export_id bigint;
begin
  if p_user_id is null
     or not exists (select 1 from auth.users u where u.id = p_user_id) then
    raise exception 'author_backup_user_missing' using errcode = '22023';
  end if;

  -- Serialize requests per author so concurrent clicks cannot bypass the limit.
  perform pg_advisory_xact_lock(hashtext('novelight:author-backup:' || p_user_id::text));

  select count(*)::integer
    into v_recent_count
    from public.author_backup_exports e
   where e.user_id = p_user_id
     and e.requested_at >= now() - interval '1 hour';

  if v_recent_count >= 3 then
    raise exception 'author_backup_rate_limit' using errcode = 'P0001';
  end if;

  insert into public.author_backup_exports (user_id)
  values (p_user_id)
  returning id into v_export_id;

  return v_export_id;
end
$function$;

revoke all on function public.novelight_begin_author_backup_export(uuid) from public, anon, authenticated;
grant execute on function public.novelight_begin_author_backup_export(uuid) to service_role;

comment on table public.author_backup_exports is
  'Server-only audit rows for author manuscript backup requests. Manuscript text is not stored here.';
comment on function public.novelight_begin_author_backup_export(uuid) is
  'Claims one of three author-backup request slots per rolling hour and returns the audit row id.';

commit;
