-- NOVELIGHT beta: chapter grouping and transaction-safe episode ordering.
--
-- Chapters are author-managed navigation metadata only. They do not create a
-- separate evaluation, Rank, LIGHT SEED, PV, or exposure unit. Existing
-- episode IDs remain stable; only episode_number and chapter membership change
-- when an owner explicitly saves a new structure.

begin;

select pg_advisory_xact_lock(hashtext('novelight:20260917050000-chapter-episode-ordering'));

do $$
begin
  if to_regclass('public.novels') is null or to_regclass('public.episodes') is null then
    raise exception 'Required novels/episodes tables are missing';
  end if;

  if not (select relrowsecurity from pg_class where oid = 'public.novels'::regclass)
     or not (select relrowsecurity from pg_class where oid = 'public.episodes'::regclass) then
    raise exception 'RLS must remain enabled on novels and episodes';
  end if;

  if to_regclass('public.novel_chapters') is not null then
    raise exception 'public.novel_chapters already exists; stop and inspect before applying';
  end if;

  if exists (
    select 1
      from information_schema.columns
     where table_schema = 'public'
       and table_name = 'episodes'
       and column_name = 'chapter_id'
  ) then
    raise exception 'episodes.chapter_id already exists; stop and inspect before applying';
  end if;

  if exists (
    select 1
      from public.episodes
     where episode_number is null or episode_number < 1
  ) then
    raise exception 'All existing episode numbers must be positive before enabling atomic reordering';
  end if;

  if exists (
    select 1
      from public.episodes
     group by novel_id, episode_number
    having count(*) > 1
  ) then
    raise exception 'Duplicate episode numbers must be resolved before enabling atomic reordering';
  end if;

  if to_regprocedure('public.novelight_create_novel_chapter(bigint,text)') is not null
     or to_regprocedure('public.novelight_rename_novel_chapter(bigint,text)') is not null
     or to_regprocedure('public.novelight_delete_novel_chapter(bigint)') is not null
     or to_regprocedure('public.novelight_reorder_novel_structure(bigint,jsonb,jsonb)') is not null
     or to_regprocedure('public.novelight_novel_outline(bigint)') is not null then
    raise exception 'Chapter/ordering RPC already exists; stop and inspect before applying';
  end if;
end
$$;

create table public.novel_chapters (
  id bigint generated by default as identity primary key,
  novel_id bigint not null references public.novels(id) on delete cascade,
  title text not null,
  position bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint novel_chapters_title_length check (
    char_length(trim(title)) between 1 and 120
  ),
  constraint novel_chapters_id_novel_unique unique (id, novel_id),
  constraint novel_chapters_novel_position_unique unique (novel_id, position)
);

alter table public.novel_chapters enable row level security;

revoke all on table public.novel_chapters from public, anon, authenticated;
grant select on table public.novel_chapters to authenticated;
grant all on table public.novel_chapters to service_role;

create policy novel_chapters_select_owner
on public.novel_chapters
as permissive
for select
to authenticated
using (
  exists (
    select 1
      from public.novels n
     where n.id = novel_chapters.novel_id
       and n.user_id = (select auth.uid())
  )
);

alter table public.episodes
  add column chapter_id bigint;

alter table public.episodes
  add constraint episodes_chapter_same_novel_fk
  foreign key (chapter_id, novel_id)
  references public.novel_chapters(id, novel_id)
  on delete restrict;

create index episodes_novel_chapter_number_idx
  on public.episodes (novel_id, chapter_id, episode_number);

create function public.novelight_create_novel_chapter(
  p_novel_id bigint,
  p_title text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_title text := trim(coalesce(p_title, ''));
  v_chapter_id bigint;
  v_position bigint;
  v_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_novel_id is null then
    raise exception 'Novel is required' using errcode = '22023';
  end if;
  if char_length(v_title) < 1 or char_length(v_title) > 120 then
    raise exception 'Chapter title must contain 1 to 120 characters' using errcode = '22023';
  end if;

  perform 1
    from public.novels n
   where n.id = p_novel_id
     and n.user_id = v_user_id
   for update;
  if not found then
    raise exception 'Novel not found or not owned by current user' using errcode = '42501';
  end if;

  select count(*)::integer,
         coalesce(max(c.position), 0) + 1
    into v_count, v_position
    from public.novel_chapters c
   where c.novel_id = p_novel_id;

  if v_count >= 200 then
    raise exception 'A novel can contain at most 200 chapters' using errcode = '22023';
  end if;
  if exists (
    select 1
      from public.novel_chapters c
     where c.novel_id = p_novel_id
       and c.position < 1
  ) then
    raise exception 'Chapter positions are invalid; stop and inspect before creating another chapter' using errcode = '22023';
  end if;

  insert into public.novel_chapters (novel_id, title, position)
  values (p_novel_id, v_title, v_position)
  returning id into v_chapter_id;

  return v_chapter_id;
end
$$;

create function public.novelight_rename_novel_chapter(
  p_chapter_id bigint,
  p_title text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_title text := trim(coalesce(p_title, ''));
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_chapter_id is null then
    raise exception 'Chapter is required' using errcode = '22023';
  end if;
  if char_length(v_title) < 1 or char_length(v_title) > 120 then
    raise exception 'Chapter title must contain 1 to 120 characters' using errcode = '22023';
  end if;

  update public.novel_chapters c
     set title = v_title,
         updated_at = now()
   where c.id = p_chapter_id
     and exists (
       select 1
         from public.novels n
        where n.id = c.novel_id
          and n.user_id = v_user_id
     );

  if not found then
    raise exception 'Chapter not found or not owned by current user' using errcode = '42501';
  end if;

  return true;
end
$$;

create function public.novelight_delete_novel_chapter(
  p_chapter_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_novel_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_chapter_id is null then
    raise exception 'Chapter is required' using errcode = '22023';
  end if;

  select c.novel_id
    into v_novel_id
    from public.novel_chapters c
    join public.novels n on n.id = c.novel_id
   where c.id = p_chapter_id
     and n.user_id = v_user_id
   for update of c, n;

  if not found then
    raise exception 'Chapter not found or not owned by current user' using errcode = '42501';
  end if;

  update public.episodes e
     set chapter_id = null
   where e.novel_id = v_novel_id
     and e.chapter_id = p_chapter_id;

  delete from public.novel_chapters c
   where c.id = p_chapter_id
     and c.novel_id = v_novel_id;

  update public.novel_chapters c
     set position = -c.position,
         updated_at = now()
   where c.novel_id = v_novel_id;

  with ordered as (
    select c.id,
           row_number() over (order by abs(c.position), c.id)::bigint as new_position
      from public.novel_chapters c
     where c.novel_id = v_novel_id
  )
  update public.novel_chapters c
     set position = ordered.new_position,
         updated_at = now()
    from ordered
   where c.id = ordered.id;

  return true;
end
$$;

create function public.novelight_reorder_novel_structure(
  p_novel_id bigint,
  p_episode_items jsonb,
  p_chapter_order jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_episode_count integer;
  v_chapter_count integer;
  v_requested_episode_count integer;
  v_requested_chapter_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_novel_id is null then
    raise exception 'Novel is required' using errcode = '22023';
  end if;
  if p_episode_items is null or jsonb_typeof(p_episode_items) <> 'array' then
    raise exception 'Episode ordering must be a JSON array' using errcode = '22023';
  end if;
  if p_chapter_order is null or jsonb_typeof(p_chapter_order) <> 'array' then
    raise exception 'Chapter ordering must be a JSON array' using errcode = '22023';
  end if;

  perform 1
    from public.novels n
   where n.id = p_novel_id
     and n.user_id = v_user_id
   for update;
  if not found then
    raise exception 'Novel not found or not owned by current user' using errcode = '42501';
  end if;

  select count(*)::integer
    into v_episode_count
    from public.episodes e
   where e.novel_id = p_novel_id;

  select count(*)::integer
    into v_chapter_count
    from public.novel_chapters c
   where c.novel_id = p_novel_id;

  if v_episode_count > 1000 then
    raise exception 'A single reorder can contain at most 1000 episodes' using errcode = '22023';
  end if;
  if v_chapter_count > 200 then
    raise exception 'A single reorder can contain at most 200 chapters' using errcode = '22023';
  end if;

  select count(*)::integer
    into v_requested_episode_count
    from jsonb_array_elements(p_episode_items);
  select count(*)::integer
    into v_requested_chapter_count
    from jsonb_array_elements(p_chapter_order);

  if v_requested_episode_count <> v_episode_count then
    raise exception 'Episode ordering must contain every episode exactly once' using errcode = '22023';
  end if;
  if v_requested_chapter_count <> v_chapter_count then
    raise exception 'Chapter ordering must contain every chapter exactly once' using errcode = '22023';
  end if;

  if exists (
    select 1
      from jsonb_array_elements(p_episode_items) item
     where jsonb_typeof(item) <> 'object'
        or coalesce(item ->> 'episode_id', '') !~ '^[1-9][0-9]*$'
        or (
          item ? 'chapter_id'
          and jsonb_typeof(item -> 'chapter_id') <> 'null'
          and coalesce(item ->> 'chapter_id', '') !~ '^[1-9][0-9]*$'
        )
  ) then
    raise exception 'Each episode item requires a positive episode_id and an optional positive chapter_id' using errcode = '22023';
  end if;

  if exists (
    select 1
      from jsonb_array_elements_text(p_chapter_order) value
     where value !~ '^[1-9][0-9]*$'
  ) then
    raise exception 'Each chapter id must be a positive integer' using errcode = '22023';
  end if;

  if (
    select count(*)
      from jsonb_array_elements(p_episode_items)
  ) <> (
    select count(distinct (item ->> 'episode_id')::bigint)
      from jsonb_array_elements(p_episode_items) item
  ) then
    raise exception 'Episode ordering contains duplicate episode ids' using errcode = '22023';
  end if;

  if (
    select count(*)
      from jsonb_array_elements_text(p_chapter_order)
  ) <> (
    select count(distinct value::bigint)
      from jsonb_array_elements_text(p_chapter_order) value
  ) then
    raise exception 'Chapter ordering contains duplicate chapter ids' using errcode = '22023';
  end if;

  if exists (
    select 1
      from jsonb_array_elements(p_episode_items) item
     where not exists (
       select 1
         from public.episodes e
        where e.id = (item ->> 'episode_id')::bigint
          and e.novel_id = p_novel_id
          and e.user_id = v_user_id
     )
  ) then
    raise exception 'Episode ordering contains an episode outside the owned novel' using errcode = '42501';
  end if;

  if exists (
    select 1
      from jsonb_array_elements(p_episode_items) item
     where item ? 'chapter_id'
       and jsonb_typeof(item -> 'chapter_id') <> 'null'
       and not exists (
         select 1
           from public.novel_chapters c
          where c.id = (item ->> 'chapter_id')::bigint
            and c.novel_id = p_novel_id
       )
  ) then
    raise exception 'Episode ordering contains a chapter outside the owned novel' using errcode = '42501';
  end if;

  if exists (
    select 1
      from jsonb_array_elements_text(p_chapter_order) value
     where not exists (
       select 1
         from public.novel_chapters c
        where c.id = value::bigint
          and c.novel_id = p_novel_id
     )
  ) then
    raise exception 'Chapter ordering contains a chapter outside the owned novel' using errcode = '42501';
  end if;

  if exists (
    select 1
      from public.episodes e
     where e.novel_id = p_novel_id
       and e.episode_number < 1
  ) then
    raise exception 'Existing episode numbers are invalid; stop and inspect before reordering' using errcode = '22023';
  end if;
  if exists (
    select 1
      from public.novel_chapters c
     where c.novel_id = p_novel_id
       and c.position < 1
  ) then
    raise exception 'Existing chapter positions are invalid; stop and inspect before reordering' using errcode = '22023';
  end if;

  perform 1
    from public.episodes e
   where e.novel_id = p_novel_id
   order by e.id
   for update;
  perform 1
    from public.novel_chapters c
   where c.novel_id = p_novel_id
   order by c.id
   for update;

  -- Move every existing number into a disjoint temporary range first. The
  -- legacy UNIQUE(novel_id, episode_number) constraint therefore remains valid
  -- throughout the transaction even when two episodes swap positions.
  update public.episodes e
     set episode_number = -e.episode_number
   where e.novel_id = p_novel_id;

  with desired as (
    select (item ->> 'episode_id')::bigint as episode_id,
           case
             when item ? 'chapter_id' and jsonb_typeof(item -> 'chapter_id') <> 'null'
               then (item ->> 'chapter_id')::bigint
             else null
           end as chapter_id,
           ordinality::bigint as new_number
      from jsonb_array_elements(p_episode_items) with ordinality as requested(item, ordinality)
  )
  update public.episodes e
     set episode_number = desired.new_number,
         chapter_id = desired.chapter_id
    from desired
   where e.id = desired.episode_id
     and e.novel_id = p_novel_id;

  update public.novel_chapters c
     set position = -c.position,
         updated_at = now()
   where c.novel_id = p_novel_id;

  with desired as (
    select value::bigint as chapter_id,
           ordinality::bigint as new_position
      from jsonb_array_elements_text(p_chapter_order) with ordinality as requested(value, ordinality)
  )
  update public.novel_chapters c
     set position = desired.new_position,
         updated_at = now()
    from desired
   where c.id = desired.chapter_id
     and c.novel_id = p_novel_id;

  return true;
end
$$;

create function public.novelight_novel_outline(
  p_novel_id bigint
)
returns table (
  episode_id bigint,
  episode_title text,
  episode_number bigint,
  episode_status text,
  chapter_id bigint,
  chapter_title text,
  chapter_position bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_owner_id uuid;
  v_novel_status text;
  v_is_owner boolean := false;
begin
  if p_novel_id is null then
    return;
  end if;

  select n.user_id, n.status
    into v_owner_id, v_novel_status
    from public.novels n
   where n.id = p_novel_id;

  if not found then
    return;
  end if;

  v_is_owner := v_user_id is not null and v_user_id = v_owner_id;
  if not v_is_owner and v_novel_status <> 'published' then
    return;
  end if;

  return query
  select e.id,
         e.title,
         e.episode_number,
         e.status,
         c.id,
         c.title,
         c.position
    from public.episodes e
    left join public.novel_chapters c
      on c.id = e.chapter_id
     and c.novel_id = e.novel_id
   where e.novel_id = p_novel_id
     and (
       v_is_owner
       or (v_novel_status = 'published' and e.status = 'published')
     )
   order by e.episode_number, e.id;
end
$$;

revoke all on function public.novelight_create_novel_chapter(bigint, text) from public, anon;
revoke all on function public.novelight_rename_novel_chapter(bigint, text) from public, anon;
revoke all on function public.novelight_delete_novel_chapter(bigint) from public, anon;
revoke all on function public.novelight_reorder_novel_structure(bigint, jsonb, jsonb) from public, anon;
revoke all on function public.novelight_novel_outline(bigint) from public;

grant execute on function public.novelight_create_novel_chapter(bigint, text) to authenticated;
grant execute on function public.novelight_rename_novel_chapter(bigint, text) to authenticated;
grant execute on function public.novelight_delete_novel_chapter(bigint) to authenticated;
grant execute on function public.novelight_reorder_novel_structure(bigint, jsonb, jsonb) to authenticated;
grant execute on function public.novelight_novel_outline(bigint) to anon, authenticated;

commit;
