-- NOVELIGHT competitor-audit item #5: author-managed novel series.
-- Series group works for navigation only. They do not create a second
-- evaluation, ranking, PV, favorite, LIGHT SEED, or exposure unit.

begin;

select pg_advisory_xact_lock(hashtext('novelight:20260917040000-novel-series'));

create table public.novel_series (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint novel_series_title_length check (
    char_length(btrim(title)) between 1 and 120
  ),
  constraint novel_series_description_length check (
    char_length(description) <= 2000
  )
);

create table public.novel_series_items (
  series_id bigint not null references public.novel_series(id) on delete cascade,
  novel_id bigint not null references public.novels(id) on delete cascade,
  position integer not null,
  created_at timestamptz not null default now(),
  primary key (series_id, novel_id),
  constraint novel_series_items_novel_once unique (novel_id),
  constraint novel_series_items_position_once unique (series_id, position),
  constraint novel_series_items_positive_position check (position > 0)
);

create index novel_series_user_id_idx on public.novel_series(user_id);
create index novel_series_items_series_position_idx
  on public.novel_series_items(series_id, position);

alter table public.novel_series enable row level security;
alter table public.novel_series_items enable row level security;

revoke all on table public.novel_series from public, anon, authenticated;
revoke all on table public.novel_series_items from public, anon, authenticated;
revoke all on sequence public.novel_series_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.novel_series to authenticated;
grant select, insert, update, delete on table public.novel_series_items to authenticated;
grant usage, select on sequence public.novel_series_id_seq to authenticated;

grant all on table public.novel_series to service_role;
grant all on table public.novel_series_items to service_role;
grant all on sequence public.novel_series_id_seq to service_role;

create policy novel_series_select_owner
on public.novel_series
for select
to authenticated
using (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
);

create policy novel_series_insert_owner
on public.novel_series
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
);

create policy novel_series_update_owner
on public.novel_series
for update
to authenticated
using (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
)
with check (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
);

create policy novel_series_delete_owner
on public.novel_series
for delete
to authenticated
using (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
);

create policy novel_series_items_select_owner
on public.novel_series_items
for select
to authenticated
using (
  (select auth.uid()) is not null
  and exists (
    select 1
    from public.novel_series s
    where s.id = novel_series_items.series_id
      and s.user_id = (select auth.uid())
  )
);

create policy novel_series_items_insert_owner
on public.novel_series_items
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and exists (
    select 1
    from public.novel_series s
    where s.id = novel_series_items.series_id
      and s.user_id = (select auth.uid())
  )
  and exists (
    select 1
    from public.novels n
    where n.id = novel_series_items.novel_id
      and n.user_id = (select auth.uid())
  )
);

create policy novel_series_items_update_owner
on public.novel_series_items
for update
to authenticated
using (
  (select auth.uid()) is not null
  and exists (
    select 1
    from public.novel_series s
    where s.id = novel_series_items.series_id
      and s.user_id = (select auth.uid())
  )
)
with check (
  (select auth.uid()) is not null
  and exists (
    select 1
    from public.novel_series s
    where s.id = novel_series_items.series_id
      and s.user_id = (select auth.uid())
  )
  and exists (
    select 1
    from public.novels n
    where n.id = novel_series_items.novel_id
      and n.user_id = (select auth.uid())
  )
);

create policy novel_series_items_delete_owner
on public.novel_series_items
for delete
to authenticated
using (
  (select auth.uid()) is not null
  and exists (
    select 1
    from public.novel_series s
    where s.id = novel_series_items.series_id
      and s.user_id = (select auth.uid())
  )
);

create or replace function public.novelight_set_series_items(
  p_series_id bigint,
  p_novel_ids bigint[] default '{}'::bigint[]
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_owner uuid;
  v_count integer := coalesce(cardinality(p_novel_ids), 0);
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;

  select s.user_id
    into v_owner
    from public.novel_series s
   where s.id = p_series_id
   for update;

  if v_owner is null or v_owner <> v_uid then
    raise exception 'SERIES_NOT_FOUND' using errcode = '42501';
  end if;

  if v_count > 100 then
    raise exception 'SERIES_ITEM_LIMIT';
  end if;

  if exists (select 1 from unnest(p_novel_ids) as x(novel_id) where novel_id is null) then
    raise exception 'SERIES_ITEM_INVALID';
  end if;

  if (
    select count(*)
      from unnest(p_novel_ids) as x(novel_id)
  ) <> (
    select count(distinct novel_id)
      from unnest(p_novel_ids) as x(novel_id)
  ) then
    raise exception 'SERIES_ITEM_DUPLICATE';
  end if;

  if (
    select count(*)
      from public.novels n
     where n.id = any(p_novel_ids)
       and n.user_id = v_uid
  ) <> v_count then
    raise exception 'SERIES_ITEM_NOT_OWNED' using errcode = '42501';
  end if;

  if exists (
    select 1
      from public.novel_series_items existing
     where existing.novel_id = any(p_novel_ids)
       and existing.series_id <> p_series_id
  ) then
    raise exception 'NOVEL_ALREADY_IN_SERIES';
  end if;

  delete from public.novel_series_items
   where series_id = p_series_id;

  insert into public.novel_series_items (series_id, novel_id, position)
  select p_series_id, item.novel_id, item.ordinality::integer
    from unnest(p_novel_ids) with ordinality as item(novel_id, ordinality);

  update public.novel_series
     set updated_at = now()
   where id = p_series_id;
end;
$$;

revoke all on function public.novelight_set_series_items(bigint, bigint[]) from public, anon, authenticated;
grant execute on function public.novelight_set_series_items(bigint, bigint[]) to authenticated;
grant execute on function public.novelight_set_series_items(bigint, bigint[]) to service_role;

create or replace function public.novelight_public_series_context(p_novel_id bigint)
returns table (
  series_id bigint,
  series_title text,
  series_description text,
  item_novel_id bigint,
  item_title text,
  item_position integer,
  is_current boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with target as (
    select n.id, n.user_id, n.status
      from public.novels n
     where n.id = p_novel_id
       and (
         n.status = 'published'
         or (
           auth.uid() is not null
           and n.user_id = auth.uid()
         )
       )
  ), target_series as (
    select i.series_id
      from public.novel_series_items i
      join target t on t.id = i.novel_id
     limit 1
  )
  select
    s.id,
    s.title,
    s.description,
    n.id,
    n.title,
    i.position,
    n.id = p_novel_id
  from target_series ts
  join public.novel_series s on s.id = ts.series_id
  join public.novel_series_items i on i.series_id = s.id
  join public.novels n on n.id = i.novel_id
  where
    n.status = 'published'
    or (
      auth.uid() is not null
      and n.user_id = auth.uid()
      and s.user_id = auth.uid()
    )
  order by i.position asc;
$$;

revoke all on function public.novelight_public_series_context(bigint) from public, anon, authenticated;
grant execute on function public.novelight_public_series_context(bigint) to anon, authenticated;
grant execute on function public.novelight_public_series_context(bigint) to service_role;

comment on table public.novel_series is
  'Author-owned navigation grouping. Not an evaluation or exposure unit.';
comment on table public.novel_series_items is
  'Ordered work membership for author-owned series.';

commit;
