-- NOVELIGHT initial schema baseline for reproducible fresh environments.
--
-- Historical context:
-- The production project originally created these core objects manually before
-- migrations were committed to Git. Later migrations therefore assume these
-- objects already exist. This baseline closes that gap for Preview/Staging and
-- local clean-room rebuilds.
--
-- Production safety:
-- If all four historical core tables already exist, this migration is a strict
-- no-op. If only some exist, it aborts instead of guessing or mutating them.

begin;

select pg_advisory_xact_lock(hashtext('novelight:20260815000000-initial-schema-baseline'));

do $baseline$
declare
  v_existing integer;
begin
  select count(*)::integer
    into v_existing
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relkind in ('r', 'p')
     and c.relname in ('profiles', 'novels', 'episodes', 'favorites');

  if v_existing = 4 then
    raise notice 'NOVELIGHT core tables already exist; baseline is a no-op.';
    return;
  end if;

  if v_existing <> 0 then
    raise exception
      'Initial schema baseline found only % of 4 required core tables; stop and inspect before continuing',
      v_existing;
  end if;

  if to_regclass('auth.users') is null then
    raise exception 'auth.users is required before applying the NOVELIGHT baseline';
  end if;

  execute $ddl$
    create table public.profiles (
      id uuid primary key,
      created_at timestamptz not null default now(),
      display_name text,
      bio text,
      plan text default 'free',
      stripe_customer_id text,
      payment_status text default 'active'
    )
  $ddl$;

  execute $ddl$
    create table public.novels (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      user_id uuid references auth.users(id),
      title text,
      description text,
      genre text,
      status text default 'draft',
      pv bigint default 0,
      favorites bigint default 0
    )
  $ddl$;

  execute $ddl$
    create table public.episodes (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      novel_id bigint references public.novels(id),
      user_id uuid references auth.users(id),
      episode_number bigint,
      title text,
      content text,
      status text default 'draft',
      pv bigint default 0
    )
  $ddl$;

  execute $ddl$
    create table public.favorites (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      user_id uuid references auth.users(id) on delete cascade,
      novel_id bigint references public.novels(id) on delete cascade
    )
  $ddl$;

  -- This unique index existed before the first committed migration. The later
  -- security migration also adds a UNIQUE constraint after validating data.
  execute 'create unique index favorites_user_novel_unique on public.favorites (user_id, novel_id)';

  execute 'alter table public.profiles enable row level security';
  execute 'alter table public.favorites enable row level security';

  execute $ddl$
    create policy "Anyone can view public profiles"
      on public.profiles
      for select
      to authenticated, anon
      using (true)
  $ddl$;

  execute $ddl$
    create policy "Users can insert own profile"
      on public.profiles
      for insert
      to authenticated
      with check (auth.uid() = id)
  $ddl$;

  execute $ddl$
    create policy "Users can update own profile"
      on public.profiles
      for update
      to authenticated
      using (auth.uid() = id)
      with check (auth.uid() = id)
  $ddl$;

  execute $ddl$
    create policy "Users can view own profile"
      on public.profiles
      for select
      to authenticated
      using (auth.uid() = id)
  $ddl$;

  execute $ddl$
    create policy "Users can add own favorites"
      on public.favorites
      for insert
      with check ((select auth.uid()) = user_id)
  $ddl$;

  execute $ddl$
    create policy "Users can delete own favorites"
      on public.favorites
      for delete
      using ((select auth.uid()) = user_id)
  $ddl$;

  execute $ddl$
    create policy "Users can read favorites"
      on public.favorites
      for select
      using (true)
  $ddl$;

  execute $ddl$
    create function public.handle_new_user()
    returns trigger
    language plpgsql
    security definer
    set search_path = public
    as $fn$
    begin
      insert into public.profiles (id, plan)
      values (new.id, 'free')
      on conflict (id) do nothing;

      return new;
    end;
    $fn$
  $ddl$;

  execute $ddl$
    create function public.increment_novel_pv(target_novel_id bigint)
    returns void
    language plpgsql
    security definer
    set search_path = public
    as $fn$
    begin
      update public.novels
         set pv = coalesce(pv, 0) + 1
       where id = target_novel_id;
    end;
    $fn$
  $ddl$;

  execute $ddl$
    create function public.increment_episode_pv(target_episode_id bigint)
    returns void
    language plpgsql
    security definer
    set search_path = public
    as $fn$
    begin
      update public.episodes
         set pv = coalesce(pv, 0) + 1
       where id = target_episode_id;
    end;
    $fn$
  $ddl$;

  execute $ddl$
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute function public.handle_new_user()
  $ddl$;

  execute 'grant all on table public.profiles, public.novels, public.episodes, public.favorites to anon, authenticated, service_role';
  execute 'grant all on sequence public.novels_id_seq, public.episodes_id_seq, public.favorites_id_seq to anon, authenticated, service_role';
  execute 'grant all on function public.handle_new_user() to anon, authenticated, service_role';
  execute 'grant all on function public.increment_novel_pv(bigint) to anon, authenticated, service_role';
  execute 'grant all on function public.increment_episode_pv(bigint) to anon, authenticated, service_role';
end
$baseline$;

commit;
