-- NOVELIGHT beta: author-owned bulk episode import with analytics.
--
-- This migration adds a safer 1-100 episode import path. Imported episodes are
-- always private drafts. The existing beta import RPC remains available for
-- compatibility and is not modified here.

begin;

select pg_advisory_xact_lock(hashtext('novelrise:20260921120552'));

do $$
begin
  if to_regclass('public.novels') is null
     or to_regclass('public.episodes') is null
     or to_regclass('public.profiles') is null then
    raise exception 'Required profiles/novels/episodes tables are missing';
  end if;

  if not (select relrowsecurity from pg_class where oid = 'public.novels'::regclass)
     or not (select relrowsecurity from pg_class where oid = 'public.episodes'::regclass) then
    raise exception 'RLS must remain enabled on novels and episodes';
  end if;

  if to_regprocedure('public.novelight_import_episode_drafts(bigint,jsonb)') is null then
    raise exception 'Existing beta episode import RPC is missing';
  end if;

  if to_regclass('public.bulk_import_events') is not null
     or to_regprocedure('public.novelight_bulk_import_episode_drafts(bigint,jsonb)') is not null
     or to_regprocedure('public.novelight_record_bulk_import_event(text,bigint,integer)') is not null then
    raise exception 'Bulk import beta objects already exist; stop and inspect before applying';
  end if;
end
$$;

create table public.bulk_import_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  novel_id bigint references public.novels(id) on delete cascade,
  event_name text not null,
  episode_count integer not null default 0,
  created_at timestamptz not null default now(),
  constraint bulk_import_events_event_name_check
    check (
      event_name in (
        'bulk_import_opened',
        'bulk_import_started',
        'bulk_import_parsed',
        'bulk_import_parse_failed',
        'bulk_import_confirmed',
        'bulk_import_completed'
      )
    ),
  constraint bulk_import_events_episode_count_check
    check (episode_count between 0 and 100)
);

alter table public.bulk_import_events enable row level security;

revoke all on table public.bulk_import_events from public;
revoke all on table public.bulk_import_events from anon;
revoke all on table public.bulk_import_events from authenticated;

create index bulk_import_events_user_created_idx
  on public.bulk_import_events (user_id, created_at desc);

create index bulk_import_events_novel_created_idx
  on public.bulk_import_events (novel_id, created_at desc)
  where novel_id is not null;

create function public.novelight_bulk_import_episode_drafts(
  p_novel_id bigint,
  p_items jsonb
)
returns integer
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_item jsonb;
  v_key text;
  v_title text;
  v_content text;
  v_start_number bigint;
  v_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if p_novel_id is null then
    raise exception 'Novel is required' using errcode = '22023';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Import items must be a JSON array' using errcode = '22023';
  end if;

  v_count := jsonb_array_length(p_items);
  if v_count < 1 or v_count > 100 then
    raise exception 'Import must contain between 1 and 100 episodes' using errcode = '22023';
  end if;

  perform 1
  from public.novels n
  where n.id = p_novel_id
    and n.user_id = v_user_id
  for update;

  if not found then
    raise exception 'Novel not found or not owned by current user' using errcode = '42501';
  end if;

  select coalesce(max(e.episode_number), 0) + 1
  into v_start_number
  from public.episodes e
  where e.novel_id = p_novel_id;

  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    if jsonb_typeof(v_item) <> 'object' then
      raise exception 'Each import item must be an object' using errcode = '22023';
    end if;

    for v_key in
      select k
      from jsonb_object_keys(v_item) as keys(k)
    loop
      if v_key not in ('title', 'content') then
        raise exception 'Unexpected import item field: %', v_key using errcode = '22023';
      end if;
    end loop;

    v_title := coalesce(v_item ->> 'title', '');
    v_content := coalesce(v_item ->> 'content', '');

    if char_length(v_title) > 150 then
      raise exception 'Each imported title must be at most 150 characters' using errcode = '22023';
    end if;

    if char_length(trim(v_content)) < 1 or char_length(v_content) > 100000 then
      raise exception 'Each imported body must contain 1 to 100000 characters' using errcode = '22023';
    end if;
  end loop;

  insert into public.episodes (
    novel_id,
    user_id,
    episode_number,
    title,
    content,
    status,
    pv
  )
  select
    p_novel_id,
    v_user_id,
    v_start_number + item.ordinality - 1,
    coalesce(item.value ->> 'title', ''),
    item.value ->> 'content',
    'draft',
    0
  from jsonb_array_elements(p_items) with ordinality as item(value, ordinality)
  order by item.ordinality;

  return v_count;
end
$$;

create function public.novelight_record_bulk_import_event(
  p_event text,
  p_novel_id bigint default null,
  p_episode_count integer default 0
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_user_id uuid := auth.uid();
  v_event text := coalesce(p_event, '');
  v_count integer := coalesce(p_episode_count, 0);
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if v_event not in (
    'bulk_import_opened',
    'bulk_import_started',
    'bulk_import_parsed',
    'bulk_import_parse_failed',
    'bulk_import_confirmed',
    'bulk_import_completed'
  ) then
    raise exception 'Unsupported bulk import event' using errcode = '22023';
  end if;

  if v_count < 0 or v_count > 100 then
    raise exception 'Episode count must be between 0 and 100' using errcode = '22023';
  end if;

  if p_novel_id is not null and not exists (
    select 1
    from public.novels n
    where n.id = p_novel_id
      and n.user_id = v_user_id
  ) then
    raise exception 'Novel not found or not owned by current user' using errcode = '42501';
  end if;

  insert into public.bulk_import_events (
    user_id,
    novel_id,
    event_name,
    episode_count
  ) values (
    v_user_id,
    p_novel_id,
    v_event,
    v_count
  );
end
$$;

revoke all on function public.novelight_bulk_import_episode_drafts(bigint,jsonb) from public;
revoke all on function public.novelight_bulk_import_episode_drafts(bigint,jsonb) from anon;
grant execute on function public.novelight_bulk_import_episode_drafts(bigint,jsonb) to authenticated;

revoke all on function public.novelight_record_bulk_import_event(text,bigint,integer) from public;
revoke all on function public.novelight_record_bulk_import_event(text,bigint,integer) from anon;
grant execute on function public.novelight_record_bulk_import_event(text,bigint,integer) to authenticated;

commit;
