-- NOVELIGHT authoritative PV counting.
-- Browser-local throttles are only an optimization; the database owns the
-- six-hour dedupe boundary and updates episode/work counters atomically.

begin;

select pg_advisory_xact_lock(hashtext('novelrise:20260901130000'));

create table public.episode_pv_events (
  id bigint generated by default as identity primary key,
  viewer_key_hash text not null,
  episode_id_snapshot text not null,
  novel_id_snapshot text not null,
  counted_at timestamptz not null default now(),
  constraint episode_pv_events_viewer_hash_length
    check (char_length(viewer_key_hash) = 32)
);

create index episode_pv_events_viewer_episode_time_idx
  on public.episode_pv_events (viewer_key_hash, episode_id_snapshot, counted_at desc);
create index episode_pv_events_counted_at_idx
  on public.episode_pv_events (counted_at desc);

alter table public.episode_pv_events enable row level security;
revoke all on table public.episode_pv_events from public, anon, authenticated;
revoke all on sequence public.episode_pv_events_id_seq from public, anon, authenticated;

create or replace function public.record_episode_pv(
  p_episode_id text,
  p_visitor_token text default null
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_uid uuid := (select auth.uid());
  v_episode_id text;
  v_novel_id text;
  v_author_id uuid;
  v_token text := btrim(coalesce(p_visitor_token, ''));
  v_viewer_key_hash text;
  v_rows integer;
begin
  if p_episode_id is null or btrim(p_episode_id) = '' then
    return false;
  end if;

  select e.id::text, e.novel_id::text, n.user_id
    into v_episode_id, v_novel_id, v_author_id
    from public.episodes e
    join public.novels n on n.id = e.novel_id
   where e.id::text = btrim(p_episode_id)
     and e.status = 'published'
     and n.status = 'published';

  if not found then
    return false;
  end if;

  -- Never count an authenticated author's own reading.
  if v_uid is not null and v_uid = v_author_id then
    return false;
  end if;

  if v_uid is not null then
    v_viewer_key_hash := md5('user:' || v_uid::text);
  else
    if char_length(v_token) not between 8 and 200 then
      raise exception using
        errcode = '22023',
        message = 'Visitor token is invalid';
    end if;
    v_viewer_key_hash := md5('visitor:' || v_token);
  end if;

  -- Serialize only the same pseudonymous viewer/episode pair. Collisions in
  -- advisory-lock hashes can add harmless serialization but cannot create a
  -- false count because the event lookup still compares the full keys.
  perform pg_advisory_xact_lock(
    hashtext(v_viewer_key_hash),
    hashtext(v_episode_id)
  );

  if exists (
    select 1
      from public.episode_pv_events p
     where p.viewer_key_hash = v_viewer_key_hash
       and p.episode_id_snapshot = v_episode_id
       and p.counted_at >= now() - interval '6 hours'
  ) then
    return false;
  end if;

  insert into public.episode_pv_events (
    viewer_key_hash,
    episode_id_snapshot,
    novel_id_snapshot,
    counted_at
  ) values (
    v_viewer_key_hash,
    v_episode_id,
    v_novel_id,
    now()
  );

  update public.episodes
     set pv = coalesce(pv, 0) + 1
   where id::text = v_episode_id;
  get diagnostics v_rows = row_count;
  if v_rows <> 1 then
    raise exception 'PV episode disappeared during authoritative count';
  end if;

  update public.novels
     set pv = coalesce(pv, 0) + 1
   where id::text = v_novel_id;
  get diagnostics v_rows = row_count;
  if v_rows <> 1 then
    raise exception 'PV work disappeared during authoritative count';
  end if;

  return true;
end
$$;

revoke all on function public.record_episode_pv(text, text) from public;
grant execute on function public.record_episode_pv(text, text) to anon, authenticated;

-- The legacy RPCs trusted any browser caller and allowed direct counter writes.
-- Keep them for server/internal compatibility, but remove every browser/public
-- execution path. Conditional DDL keeps compact integration fixtures valid.
do $$
begin
  if to_regprocedure('public.increment_novel_pv(bigint)') is not null then
    execute 'revoke all on function public.increment_novel_pv(bigint) from public, anon, authenticated';
  end if;

  if to_regprocedure('public.increment_episode_pv(bigint)') is not null then
    execute 'revoke all on function public.increment_episode_pv(bigint) from public, anon, authenticated';
  end if;
end
$$;

commit;
