-- NOVELIGHT B #9: author follows with in-app new-work / update notifications.
-- Follow relationships are convenience data only and never affect Rank, discovery, or SCOUT.
-- Publication events are stored once; follower rows keep independent cursors without fan-out.

begin;

select pg_advisory_xact_lock(hashtext('novelight:20260918140022'));

do $$
begin
  if to_regclass('public.profiles') is null
     or to_regclass('public.novels') is null
     or to_regclass('public.episodes') is null
     or to_regclass('public.user_blocks') is null
     or to_regclass('public.user_mutes') is null then
    raise exception 'Author follow prerequisites are missing';
  end if;

  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public'
       and table_name = 'novels'
       and column_name = 'first_published_at'
  ) then
    raise exception 'novels.first_published_at is required';
  end if;
  if to_regclass('public.author_follows') is not null
     or to_regclass('public.author_follow_events') is not null
     or to_regprocedure('public.novelight_author_follow_state(uuid)') is not null
     or to_regprocedure('public.novelight_set_author_follow(uuid,boolean)') is not null
     or to_regprocedure('public.novelight_set_author_follow_notifications(uuid,boolean,boolean)') is not null
     or to_regprocedure('public.novelight_followed_author_updates(integer)') is not null
     or to_regprocedure('public.novelight_mark_author_follow_updates_seen(uuid,bigint,bigint)') is not null
     or to_regprocedure('public.novelight_capture_author_follow_event()') is not null then
    raise exception 'Author follow objects already exist; stop and inspect';
  end if;
end
$$;

create table public.author_follows (
  follower_user_id uuid not null references public.profiles(id) on delete cascade,
  author_user_id uuid not null references public.profiles(id) on delete cascade,
  notify_new_works boolean not null default true,
  notify_updates boolean not null default true,
  new_work_seen_event_id bigint not null default 0,
  update_seen_event_id bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (follower_user_id, author_user_id),
  constraint author_follows_no_self check (follower_user_id <> author_user_id),
  constraint author_follows_new_work_cursor_nonnegative check (new_work_seen_event_id >= 0),
  constraint author_follows_update_cursor_nonnegative check (update_seen_event_id >= 0)
);

create table public.author_follow_events (
  id bigint generated by default as identity primary key,
  author_user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null
    check (event_type in ('novel_published', 'episode_published')),
  novel_id bigint not null references public.novels(id) on delete cascade,
  episode_id bigint references public.episodes(id) on delete cascade,
  occurred_at timestamptz not null default now(),
  constraint author_follow_events_payload_shape check (
    (event_type = 'novel_published' and episode_id is null)
    or (event_type = 'episode_published' and episode_id is not null)
  )
);

create index author_follows_author_idx
  on public.author_follows (author_user_id, follower_user_id);

create index author_follow_events_author_cursor_idx
  on public.author_follow_events (author_user_id, id desc);

create unique index author_follow_events_novel_once_idx
  on public.author_follow_events (novel_id)
  where event_type = 'novel_published';

create unique index author_follow_events_episode_once_idx
  on public.author_follow_events (episode_id)
  where event_type = 'episode_published';

alter table public.author_follows enable row level security;
alter table public.author_follow_events enable row level security;

revoke all on table public.author_follows from public, anon, authenticated;
revoke all on table public.author_follow_events from public, anon, authenticated;
revoke all on sequence public.author_follow_events_id_seq from public, anon, authenticated;

create function public.novelight_capture_author_follow_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_author_user_id uuid;
begin
  if tg_table_name = 'novels' then
    if new.user_id is null or new.status <> 'published' then
      return new;
    end if;

    if tg_op = 'INSERT' then
      insert into public.author_follow_events(
        author_user_id, event_type, novel_id, episode_id, occurred_at
      ) values (
        new.user_id,
        'novel_published',
        new.id,
        null,
        coalesce(new.first_published_at, pg_catalog.now())
      )
      on conflict do nothing;
    elsif old.status is distinct from 'published' then
      insert into public.author_follow_events(
        author_user_id, event_type, novel_id, episode_id, occurred_at
      ) values (
        new.user_id,
        'novel_published',
        new.id,
        null,
        coalesce(new.first_published_at, pg_catalog.now())
      )
      on conflict do nothing;
    end if;

    return new;
  end if;

  if tg_table_name = 'episodes' then
    if new.novel_id is null or new.status <> 'published' then
      return new;
    end if;

    -- Episode 1 belongs to the new-work notification. Emitting a separate
    -- update event for it would notify the same publication twice.
    if coalesce(new.episode_number, 0) <= 1 then
      return new;
    end if;

    if tg_op = 'UPDATE' and old.status is not distinct from 'published' then
      return new;
    end if;

    select n.user_id
      into v_author_user_id
      from public.novels n
     where n.id = new.novel_id
       and n.status = 'published';

    if v_author_user_id is not null then
      insert into public.author_follow_events(
        author_user_id, event_type, novel_id, episode_id, occurred_at
      ) values (
        v_author_user_id,
        'episode_published',
        new.novel_id,
        new.id,
        pg_catalog.now()
      )
      on conflict do nothing;
    end if;
  end if;

  return new;
end
$$;

create trigger novelight_author_follow_novel_publication
after insert or update of status on public.novels
for each row
execute function public.novelight_capture_author_follow_event();

create trigger novelight_author_follow_episode_publication
after insert or update of status on public.episodes
for each row
execute function public.novelight_capture_author_follow_event();

create function public.novelight_author_follow_state(p_author_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_row public.author_follows%rowtype;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  if p_author_user_id is null or p_author_user_id = v_uid then
    raise exception using errcode = '22023', message = 'Invalid author';
  end if;
  if not exists(select 1 from public.profiles p where p.id = p_author_user_id) then
    raise exception using errcode = '23503', message = 'Author not found';
  end if;

  select *
    into v_row
    from public.author_follows f
   where f.follower_user_id = v_uid
     and f.author_user_id = p_author_user_id;

  if not found then
    return pg_catalog.jsonb_build_object(
      'following', false,
      'notify_new_works', true,
      'notify_updates', true
    );
  end if;

  return pg_catalog.jsonb_build_object(
    'following', true,
    'notify_new_works', v_row.notify_new_works,
    'notify_updates', v_row.notify_updates
  );
end
$$;

create function public.novelight_set_author_follow(
  p_author_user_id uuid,
  p_following boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_new_work_cursor bigint := 0;
  v_update_cursor bigint := 0;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  if p_author_user_id is null or p_author_user_id = v_uid or p_following is null then
    raise exception using errcode = '22023', message = 'Invalid follow request';
  end if;
  if not exists(select 1 from public.profiles p where p.id = p_author_user_id) then
    raise exception using errcode = '23503', message = 'Author not found';
  end if;

  if p_following then
    if exists(
      select 1
        from public.user_blocks b
       where (b.blocker_user_id = v_uid and b.blocked_user_id = p_author_user_id)
          or (b.blocker_user_id = p_author_user_id and b.blocked_user_id = v_uid)
    ) then
      raise exception using errcode = '42501', message = 'DIRECT_INTERACTION_UNAVAILABLE';
    end if;

    select coalesce(pg_catalog.max(e.id), 0)
      into v_new_work_cursor
      from public.author_follow_events e
     where e.author_user_id = p_author_user_id
       and e.event_type = 'novel_published';

    select coalesce(pg_catalog.max(e.id), 0)
      into v_update_cursor
      from public.author_follow_events e
     where e.author_user_id = p_author_user_id
       and e.event_type = 'episode_published';

    insert into public.author_follows(
      follower_user_id,
      author_user_id,
      new_work_seen_event_id,
      update_seen_event_id
    ) values (
      v_uid,
      p_author_user_id,
      v_new_work_cursor,
      v_update_cursor
    )
    on conflict (follower_user_id, author_user_id) do nothing;
  else
    delete from public.author_follows f
     where f.follower_user_id = v_uid
       and f.author_user_id = p_author_user_id;
  end if;

  return public.novelight_author_follow_state(p_author_user_id);
end
$$;

create function public.novelight_set_author_follow_notifications(
  p_author_user_id uuid,
  p_notify_new_works boolean,
  p_notify_updates boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_follow public.author_follows%rowtype;
  v_new_work_cursor bigint;
  v_update_cursor bigint;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  if p_author_user_id is null
     or p_notify_new_works is null
     or p_notify_updates is null then
    raise exception using errcode = '22023', message = 'Invalid notification settings';
  end if;

  select *
    into v_follow
    from public.author_follows f
   where f.follower_user_id = v_uid
     and f.author_user_id = p_author_user_id
   for update;

  if not found then
    raise exception using errcode = '23514', message = 'Author is not followed';
  end if;

  v_new_work_cursor := v_follow.new_work_seen_event_id;
  v_update_cursor := v_follow.update_seen_event_id;

  if p_notify_new_works and not v_follow.notify_new_works then
    select coalesce(pg_catalog.max(e.id), 0)
      into v_new_work_cursor
      from public.author_follow_events e
     where e.author_user_id = p_author_user_id
       and e.event_type = 'novel_published';
  end if;

  if p_notify_updates and not v_follow.notify_updates then
    select coalesce(pg_catalog.max(e.id), 0)
      into v_update_cursor
      from public.author_follow_events e
     where e.author_user_id = p_author_user_id
       and e.event_type = 'episode_published';
  end if;

  update public.author_follows f
     set notify_new_works = p_notify_new_works,
         notify_updates = p_notify_updates,
         new_work_seen_event_id = v_new_work_cursor,
         update_seen_event_id = v_update_cursor,
         updated_at = pg_catalog.now()
   where f.follower_user_id = v_uid
     and f.author_user_id = p_author_user_id;

  return public.novelight_author_follow_state(p_author_user_id);
end
$$;

create function public.novelight_followed_author_updates(p_limit integer default 50)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 100);
  v_result jsonb;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  select coalesce(
    pg_catalog.jsonb_agg(q.item order by q.event_id desc),
    '[]'::jsonb
  )
    into v_result
    from (
      select
        e.id as event_id,
        pg_catalog.jsonb_build_object(
          'event_id', e.id::text,
          'event_type', e.event_type,
          'occurred_at', e.occurred_at,
          'author_user_id', e.author_user_id::text,
          'author_display_name', coalesce(p.display_name, '名前未設定'),
          'novel_id', n.id::text,
          'novel_title', coalesce(n.title, 'タイトル未設定'),
          'episode_id', case when ep.id is null then null else ep.id::text end,
          'episode_number', ep.episode_number,
          'episode_title', ep.title
        ) as item
      from public.author_follows f
      join public.author_follow_events e
        on e.author_user_id = f.author_user_id
      join public.profiles p
        on p.id = e.author_user_id
      join public.novels n
        on n.id = e.novel_id
       and n.user_id = e.author_user_id
       and n.status = 'published'
      left join public.episodes ep
        on ep.id = e.episode_id
       and ep.novel_id = e.novel_id
     where f.follower_user_id = v_uid
       and (
         (
           e.event_type = 'novel_published'
           and f.notify_new_works
           and e.id > f.new_work_seen_event_id
         )
         or (
           e.event_type = 'episode_published'
           and f.notify_updates
           and e.id > f.update_seen_event_id
           and ep.status = 'published'
         )
       )
       and not exists(
         select 1 from public.user_mutes m
          where m.muter_user_id = v_uid
            and m.muted_user_id = e.author_user_id
       )
       and not exists(
         select 1 from public.user_blocks b
          where (b.blocker_user_id = v_uid and b.blocked_user_id = e.author_user_id)
             or (b.blocker_user_id = e.author_user_id and b.blocked_user_id = v_uid)
       )
     order by e.id desc
     limit v_limit
    ) q;

  return v_result;
end
$$;

create function public.novelight_mark_author_follow_updates_seen(
  p_author_user_id uuid,
  p_new_work_event_id bigint default null,
  p_update_event_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_follow public.author_follows%rowtype;
begin
  if v_uid is null then
    raise exception using errcode = '42501', message = 'Authentication required';
  end if;
  if p_author_user_id is null then
    raise exception using errcode = '22023', message = 'Invalid author';
  end if;

  select *
    into v_follow
    from public.author_follows f
   where f.follower_user_id = v_uid
     and f.author_user_id = p_author_user_id
   for update;

  if not found then
    raise exception using errcode = '23514', message = 'Author is not followed';
  end if;

  if p_new_work_event_id is not null then
    if p_new_work_event_id < 1 or not exists(
      select 1 from public.author_follow_events e
       where e.id = p_new_work_event_id
         and e.author_user_id = p_author_user_id
         and e.event_type = 'novel_published'
    ) then
      raise exception using errcode = '22023', message = 'Invalid new-work cursor';
    end if;
    v_follow.new_work_seen_event_id :=
      greatest(v_follow.new_work_seen_event_id, p_new_work_event_id);
  end if;
  if p_update_event_id is not null then
    if p_update_event_id < 1 or not exists(
      select 1 from public.author_follow_events e
       where e.id = p_update_event_id
         and e.author_user_id = p_author_user_id
         and e.event_type = 'episode_published'
    ) then
      raise exception using errcode = '22023', message = 'Invalid update cursor';
    end if;
    v_follow.update_seen_event_id :=
      greatest(v_follow.update_seen_event_id, p_update_event_id);
  end if;

  update public.author_follows f
     set new_work_seen_event_id = v_follow.new_work_seen_event_id,
         update_seen_event_id = v_follow.update_seen_event_id,
         updated_at = pg_catalog.now()
   where f.follower_user_id = v_uid
     and f.author_user_id = p_author_user_id;

  return public.novelight_author_follow_state(p_author_user_id);
end
$$;

revoke all on function public.novelight_capture_author_follow_event()
  from public, anon, authenticated, service_role;
revoke all on function public.novelight_author_follow_state(uuid)
  from public, anon;
revoke all on function public.novelight_set_author_follow(uuid, boolean)
  from public, anon;
revoke all on function public.novelight_set_author_follow_notifications(uuid, boolean, boolean)
  from public, anon;
revoke all on function public.novelight_followed_author_updates(integer)
  from public, anon;
revoke all on function public.novelight_mark_author_follow_updates_seen(uuid, bigint, bigint)
  from public, anon;

grant execute on function public.novelight_author_follow_state(uuid)
  to authenticated;
grant execute on function public.novelight_set_author_follow(uuid, boolean)
  to authenticated;
grant execute on function public.novelight_set_author_follow_notifications(uuid, boolean, boolean)
  to authenticated;
grant execute on function public.novelight_followed_author_updates(integer)
  to authenticated;
grant execute on function public.novelight_mark_author_follow_updates_seen(uuid, bigint, bigint)
  to authenticated;

commit;
